////////////////////////////////////////////////////////////////////////////////
// checkstyle: Checks Java source code for adherence to a set of rules.
// Copyright (C) 2001-2025 the original author or authors.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 3 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
////////////////////////////////////////////////////////////////////////////////

package org.sonar.plugins.checkstyle;

import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Nullable;

import org.apache.commons.lang.StringEscapeUtils;
import org.apache.commons.lang.StringUtils;
import org.sonar.api.batch.rule.ActiveRule;
import org.sonar.api.batch.rule.ActiveRules;
import org.sonar.api.config.Configuration;

import com.google.common.annotations.VisibleForTesting;

public class CheckstyleProfileExporter {

    public static final String DOCTYPE_DECLARATION =
        "<!DOCTYPE module PUBLIC \"-//Checkstyle//DTD Checkstyle Configuration 1.3//EN\" "
        + "\"https://checkstyle.org/dtds/configuration_1_3.dtd\">";
    private static final String CLOSE_MODULE = "</module>";

    private final Configuration configuration;

    public CheckstyleProfileExporter(Configuration configuration) {
        this.configuration = configuration;
    }

    /**
     * Exports the active rules to the specified writer.
     *
     * @param activeRules The rules to export.
     * @param writer The destination of the export.
     * @throws IllegalStateException if the rules failed to export.
     */
    public void exportProfile(ActiveRules activeRules, Writer writer) {
        try {
            final Map<String, List<ActiveRule>> activeRulesByConfigKey =
                    arrangeByConfigKey(activeRules
                    .findByRepository(CheckstyleConstants.REPOSITORY_KEY));
            generateXml(writer, activeRulesByConfigKey);
        }
        catch (IOException exception) {
            throw new IllegalStateException("Fail to export active rules.", exception);
        }

    }

    private void generateXml(Writer writer, Map<String,
            List<ActiveRule>> activeRulesByConfigKey) throws IOException {
        appendXmlHeader(writer);
        appendTabWidth(writer);
        appendCustomFilters(writer);
        appendCheckerModules(writer, activeRulesByConfigKey);
        appendTreeWalker(writer, activeRulesByConfigKey);
        appendXmlFooter(writer);
    }

    private static void appendXmlHeader(Writer writer) throws IOException {
        writer.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>" + DOCTYPE_DECLARATION
                + "<!-- Generated by Sonar -->" + "<module name=\"Checker\">");
    }

    private void appendCustomFilters(Writer writer) throws IOException {
        final String filtersXml = configuration.get(CheckstyleConstants.CHECKER_FILTERS_KEY)
                .orElse(null);
        writer.append(filtersXml);
    }

    private void appendTabWidth(Writer writer) throws IOException {
        final String tabWidth = configuration.get(CheckstyleConstants.CHECKER_TAB_WIDTH)
                .orElse(null);
        appendModuleProperty(writer, "tabWidth", tabWidth);
    }

    private static void appendCheckerModules(Writer writer,
            Map<String, List<ActiveRule>> activeRulesByConfigKey) throws IOException {
        for (Map.Entry<String, List<ActiveRule>> entry : activeRulesByConfigKey.entrySet()) {
            final String configKey = entry.getKey();
            if (!isInTreeWalker(configKey)) {
                final List<ActiveRule> activeRules = entry.getValue();
                for (ActiveRule activeRule : activeRules) {
                    appendModule(writer, activeRule);
                }
            }
        }
    }

    private void appendTreeWalker(Writer writer,
            Map<String, List<ActiveRule>> activeRulesByConfigKey) throws IOException {
        writer.append("<module name=\"TreeWalker\">");
        if (isSuppressWarningsEnabled()) {
            writer.append("<module name=\"SuppressWarningsHolder\"/> ");
        }
        final List<String> ruleSet = new ArrayList<>(activeRulesByConfigKey.keySet());
        Collections.sort(ruleSet);
        for (String configKey : ruleSet) {
            if (isInTreeWalker(configKey)) {
                final List<ActiveRule> activeRules = activeRulesByConfigKey.get(configKey);
                for (ActiveRule activeRule : activeRules) {
                    appendModule(writer, activeRule);
                }
            }
        }
        // append Treewalker filters
        final String filtersXml = configuration
                .get(CheckstyleConstants.TREEWALKER_FILTERS_KEY)
                .orElse(null);
        writer.append(filtersXml);

        writer.append(CLOSE_MODULE);
    }

    private boolean isSuppressWarningsEnabled() {
        final String filtersXml = configuration.get(CheckstyleConstants.CHECKER_FILTERS_KEY)
                .orElse(null);
        boolean result = false;
        if (filtersXml != null) {
            result = filtersXml.contains("<module name=\"SuppressWarningsFilter\" />");
        }
        return result;
    }

    private static void appendXmlFooter(Writer writer) throws IOException {
        writer.append(CLOSE_MODULE);
    }

    @VisibleForTesting
    static boolean isInTreeWalker(String configKey) {
        return StringUtils.startsWithIgnoreCase(configKey, "Checker/TreeWalker/");
    }

    private static Map<String, List<ActiveRule>> arrangeByConfigKey(
            Collection<ActiveRule> activeRules) {
        final Map<String, List<ActiveRule>> result = new HashMap<>();
        for (ActiveRule activeRule : activeRules) {
            final String key = activeRule.internalKey();
            if (result.containsKey(key)) {
                final List<ActiveRule> rules = result.get(key);
                rules.add(activeRule);
            }
            else {
                final List<ActiveRule> rules = new ArrayList<>();
                rules.add(activeRule);
                result.put(key, rules);
            }
        }
        return result;
    }

    private static void appendModule(Writer writer, ActiveRule activeRule)
            throws IOException {
        final String moduleName = StringUtils.substringAfterLast(activeRule.internalKey(), "/");
        writer.append("<module name=\"");
        StringEscapeUtils.escapeXml(writer, moduleName);
        writer.append("\">");
        if (activeRule.templateRuleKey() != null) {
            appendModuleProperty(writer, "id",
                                activeRule.ruleKey().rule());
        }
        appendModuleProperty(writer, "severity",
                            CheckstyleSeverityUtils.toSeverity(activeRule.severity()));
        appendRuleParameters(writer, activeRule);
        writer.append(CLOSE_MODULE);
    }

    private static void appendRuleParameters(Writer writer, ActiveRule activeRule)
            throws IOException {
        for (Map.Entry<String, String> param : activeRule.params().entrySet()) {
            if (StringUtils.isNotBlank(param.getValue())) {
                appendModuleProperty(writer, param.getKey(), param.getValue());
            }
        }
    }

    private static void appendModuleProperty(Writer writer, String propertyKey,
            @Nullable String propertyValue) throws IOException {
        if (StringUtils.isNotBlank(propertyValue)) {
            writer.append("<property name=\"");
            StringEscapeUtils.escapeXml(writer, propertyKey);
            writer.append("\" value=\"");
            StringEscapeUtils.escapeXml(writer, propertyValue);
            writer.append("\"/>");
        }
    }

}
